### ISSUE TITLE
Introduce a bundler like rollup to provide better output files for browser

### ISSUE THREAD

**Issue by Mister-Hope** [bernd-wechner/Copy-with-Style#2]
Nice project. I am wondering if you and import a bundler like rollup to provide a output bundle which targets modern browser.

I think that a smaller packed file targeting major browsers<last 1 year (I.e.: rolling version of chrome, safari, edge, firefox released in recent 12 months) benefit more developers if they want to import this package directly through cdn.

## Willing to do this myself?

Yes, call me if you need a pr like this.

**Comment by bernd-wechner** [comment]
Sure, happy to look at a PR. I'm not familiar with rollup myself but thanks for the note as it prompted a quick read. Not enough to actually work out yet how exactly you'd envisage using it on this but I'm curious.  Admit that I wrote this for a particular site I'm using and then ran (as I have loads of other jobs need doing, tee hee). But I did write it as I found nothing else lived up to what I needed (a nice simple way to copy an element to clipboard as styled HTML - which I discuss in a [dev.to article series](https://dev.to/thumbone/the-thing-is-on-awesomeness-and-motivation-2i0j) because it was a bit of a rabbit hole really, a lot ultimately to get right).

**Comment by Mister-Hope** [comment]
BTW, I know it's kind of personal taste, but most users and developers user camelCase variables in js/ts, including es built-in function and DOM APIs, so any motivation using snake_case or any plans to change back to camelCase?

(After importing this lib, my linter complains about the API syntax)

**Comment by bernd-wechner** [comment]
Resolved by https://github.com/bernd-wechner/Copy-with-Style/pull/5.

I'm not much fussed about CamelCase, camelCase or snake_case as a rule, as long as any given package is internally consistent. Clarity is my main goal. 

As an aside to pick a random, Google selected, style guide, what do you think of this one:

https://www.syncfusion.com/blogs/post/10-javascript-naming-conventions-every-developer-should-know.aspx

Or do you have a preferred one. 

As noted other-placely, I don't do a lot of JS coding (can't say I much like JS) but am compelled to hack something up now and then, as I did this, so it's done on the fly trying to get a functional alpha into the wings one whatever site is driving my need. On top of that I am driven by a passion for learning and so do a fair bit of reading (and today interaction of chatGPT ;-) but will always take an existing solution before reinventing any wheel.

Ironically, in this case I found existing solutions most wanting and lacking, mostly very dated and/or poorly documented and/or not using recent JavaScript innovations (anachronistic).
